-- PharmFlow B11 Clean 5.1 — Shared-Database Safe Pharmacy GTIN Corrections
-- SAFE FOR THE CURRENT ARCHITECTURE WHERE PROJECT A + PROJECT B SHARE ONE SUPABASE DATABASE.
-- Additive/backward-compatible: creates a NEW audit table and NEW RPC names only.
-- Production A's existing RPCs/tables/receiving behavior are not replaced.
-- IMPORTANT: this NEVER writes to the System Global GTIN Master.

begin;

do $$
begin
  if to_regclass('public.pharmacies') is null then raise exception 'Missing dependency: public.pharmacies'; end if;
  if to_regclass('public.pharmacy_members') is null then raise exception 'Missing dependency: public.pharmacy_members'; end if;
  if to_regclass('public.system_owners') is null then raise exception 'Missing dependency: public.system_owners'; end if;
  if to_regclass('public.pharmacy_learned_gtin') is null then raise exception 'Missing dependency: public.pharmacy_learned_gtin'; end if;
  if to_regprocedure('public.pharmflow_is_member(uuid)') is null then raise exception 'Missing dependency: public.pharmflow_is_member(uuid)'; end if;
end $$;

create table if not exists public.pharmacy_learned_gtin_audit (
  audit_id bigint generated by default as identity primary key,
  pharmacy_id uuid not null references public.pharmacies(id) on delete cascade,
  gtin text not null,
  old_item_code text,
  old_item_name text,
  new_item_code text,
  new_item_name text,
  action text not null check (action in ('CORRECT','REMOVE')),
  reason text not null,
  changed_by uuid default auth.uid(),
  changed_at timestamptz not null default now()
);
create index if not exists idx_pharmacy_learned_gtin_audit_lookup
  on public.pharmacy_learned_gtin_audit(pharmacy_id,gtin,changed_at desc);
alter table public.pharmacy_learned_gtin_audit enable row level security;

create or replace function public.correct_pharmacy_learned_gtin(
  p_pharmacy_id uuid,
  p_gtin text,
  p_new_item_code text,
  p_new_item_name text,
  p_reason text
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_gtin text:=regexp_replace(coalesce(p_gtin,''),'[^0-9]','','g');
  v_code text:=trim(coalesce(p_new_item_code,''));
  v_name text:=trim(coalesce(p_new_item_name,''));
  v_reason text:=trim(coalesce(p_reason,''));
  v_old public.pharmacy_learned_gtin%rowtype;
begin
  if auth.uid() is null or not public.pharmflow_is_member(p_pharmacy_id) then raise exception 'Pharmacy access required'; end if;
  if not exists(select 1 from public.system_owners so where so.user_id=auth.uid())
     and not exists(select 1 from public.pharmacy_members pm where pm.pharmacy_id=p_pharmacy_id and pm.user_id=auth.uid() and lower(coalesce(pm.member_role,''))='admin')
  then raise exception 'Pharmacy ADMIN access is required for GTIN corrections'; end if;
  if length(v_gtin)<8 or v_code='' or v_name='' or v_reason='' then raise exception 'GTIN, Item Code, Item Name and Reason are required'; end if;

  select * into v_old from public.pharmacy_learned_gtin
   where pharmacy_id=p_pharmacy_id and regexp_replace(gtin,'[^0-9]','','g')=v_gtin limit 1 for update;
  if v_old.id is null then raise exception 'No pharmacy-learned mapping exists for this GTIN'; end if;

  insert into public.pharmacy_learned_gtin_audit(pharmacy_id,gtin,old_item_code,old_item_name,new_item_code,new_item_name,action,reason)
  values(p_pharmacy_id,v_gtin,v_old.item_code,v_old.item_name,v_code,v_name,'CORRECT',v_reason);

  update public.pharmacy_learned_gtin
     set item_code=v_code,item_name=v_name,updated_at=now()
   where id=v_old.id;

  return jsonb_build_object('success',true,'scope','pharmacy','action','CORRECT','gtin',v_gtin,'old_item_code',v_old.item_code,'new_item_code',v_code);
end; $$;

create or replace function public.remove_pharmacy_learned_gtin(
  p_pharmacy_id uuid,p_gtin text,p_reason text
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_gtin text:=regexp_replace(coalesce(p_gtin,''),'[^0-9]','','g');
  v_reason text:=trim(coalesce(p_reason,''));
  v_old public.pharmacy_learned_gtin%rowtype;
begin
  if auth.uid() is null or not public.pharmflow_is_member(p_pharmacy_id) then raise exception 'Pharmacy access required'; end if;
  if not exists(select 1 from public.system_owners so where so.user_id=auth.uid())
     and not exists(select 1 from public.pharmacy_members pm where pm.pharmacy_id=p_pharmacy_id and pm.user_id=auth.uid() and lower(coalesce(pm.member_role,''))='admin')
  then raise exception 'Pharmacy ADMIN access is required for GTIN corrections'; end if;
  if length(v_gtin)<8 or v_reason='' then raise exception 'GTIN and Reason are required'; end if;

  select * into v_old from public.pharmacy_learned_gtin
   where pharmacy_id=p_pharmacy_id and regexp_replace(gtin,'[^0-9]','','g')=v_gtin limit 1 for update;
  if v_old.id is null then raise exception 'No pharmacy-learned mapping exists for this GTIN'; end if;

  insert into public.pharmacy_learned_gtin_audit(pharmacy_id,gtin,old_item_code,old_item_name,action,reason)
  values(p_pharmacy_id,v_gtin,v_old.item_code,v_old.item_name,'REMOVE',v_reason);
  delete from public.pharmacy_learned_gtin where id=v_old.id;

  return jsonb_build_object('success',true,'scope','pharmacy','action','REMOVE','gtin',v_gtin,'old_item_code',v_old.item_code);
end; $$;

revoke all on function public.correct_pharmacy_learned_gtin(uuid,text,text,text,text) from public,anon;
revoke all on function public.remove_pharmacy_learned_gtin(uuid,text,text) from public,anon;
grant execute on function public.correct_pharmacy_learned_gtin(uuid,text,text,text,text) to authenticated;
grant execute on function public.remove_pharmacy_learned_gtin(uuid,text,text) to authenticated;

commit;
